### ISSUE TITLE
Gördüğüm en berbat ödeme sistemi

### ISSUE THREAD

**Issue by hacicavcav** [wirecard/paymentSDK-php#658]
Çoğu şey manuel üstelik php ileri sürümlerinde hata basıyor. Yapacağınız işi..... diyesi geliyor insanın.

**Comment by rinnhofer** [comment]
Hello @hacicavcav,

we are sorry but without any further information and specifics on your problems we can not support you in resolving them.
We would appreciate if you could create issues only in english or german here and with useful information on what exactly does not work for you or where you would need help.

We are trying to help as good as we can and also try to be constructive in our responses and would value the same behaviour from contributors as well. Therefor I will close this issue.

Here is a short summary on how issues can be created in a constructive and beneficial way:
# Description of the problem
# Expected behaviour
# Actual behaviour
# Steps to reproduce

Kind regards,
Wirecard Shop Systems Team
